service: snowflake-translate

frameworkVersion: "2"

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket

custom:
  pythonRequirements:
    dockerizePip: non-linux

  stage: "${self:provider.stage}"


provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  runtime: python3.7
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'translate:TranslateText'
          Resource: "*"

  # role: arn:aws:iam::845977697457:role/AWSLambdaVPCSecretsExecutionRole

package:
  exclude:
    - .git/**
    - .env/**
    - node_modules/**

functions:
  snowflake-translate:
    handler: translate_from_english.handler
    events:
      - http:
          path: translate/from_english
          method: post
          # authorizer: aws_iam
    timeout: 30
    memorySize: 1024